---
volumes:
  qbittorrent:
    driver_opts:
      type: cifs
      o: "username=$QBITTORRENT_SMB_USR,password=$QBITTORRENT_SMB_PWD,addr=$QBITTORRENT_HOST,rw,uid=1006,gid=1008"
      device: "//$QBITTORRENT_SMB_HOST/qbittorrent"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      PUID: 1006
      PGID: 1008
      TZ: Etc/UTC
      WEBUI_PORT: 8080
      TORRENTING_PORT: 6881
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - qbittorrent:/downloads
    env_file: ../stack.env

